package kanji

// N4 contains all ~167 JLPT N4 kanji, ordered by frequency.
// Accepted answers for each character: any on'yomi romaji,
// any kun'yomi romaji, or any English meaning (case-insensitive).
var N4 = []Kanji{
	// Group 1 (1–10)
	{
		Char:     "会",
		Onyomi:   []string{"kai", "e"},
		Kunyomi:  []string{"au", "awaseru"},
		Meanings: []string{"meet", "meeting", "party", "association"},
	},
	{
		Char:     "同",
		Onyomi:   []string{"dou"},
		Kunyomi:  []string{"onaji"},
		Meanings: []string{"same", "equal", "identical", "agreement"},
	},
	{
		Char:     "事",
		Onyomi:   []string{"ji", "zu"},
		Kunyomi:  []string{"koto"},
		Meanings: []string{"thing", "matter", "fact", "business"},
	},
	{
		Char:     "自",
		Onyomi:   []string{"ji", "shi"},
		Kunyomi:  []string{"mizukara", "onozukara"},
		Meanings: []string{"self", "oneself"},
	},
	{
		Char:     "社",
		Onyomi:   []string{"sha"},
		Kunyomi:  []string{"yashiro"},
		Meanings: []string{"company", "shrine", "firm", "office"},
	},
	{
		Char:     "発",
		Onyomi:   []string{"hatsu", "hotsu"},
		Kunyomi:  []string{"tatsu", "abaku", "okoru", "tsukawasu"},
		Meanings: []string{"departure", "emit", "start", "publish"},
	},
	{
		Char:     "者",
		Onyomi:   []string{"sha"},
		Kunyomi:  []string{"mono"},
		Meanings: []string{"person", "someone"},
	},
	{
		Char:     "地",
		Onyomi:   []string{"chi"},
		Kunyomi:  []string{},
		Meanings: []string{"ground", "earth", "place"},
	},
	{
		Char:     "業",
		Onyomi:   []string{"gyou", "gou"},
		Kunyomi:  []string{"waza"},
		Meanings: []string{"business", "industry", "vocation", "performance"},
	},
	{
		Char:     "方",
		Onyomi:   []string{"hou"},
		Kunyomi:  []string{"kata"},
		Meanings: []string{"direction", "person", "way", "alternative"},
	},

	// Group 2 (11–20)
	{
		Char:     "新",
		Onyomi:   []string{"shin"},
		Kunyomi:  []string{"atarashii", "arata", "nii"},
		Meanings: []string{"new"},
	},
	{
		Char:     "場",
		Onyomi:   []string{"jou", "chou"},
		Kunyomi:  []string{"ba"},
		Meanings: []string{"place", "location"},
	},
	{
		Char:     "員",
		Onyomi:   []string{"in"},
		Kunyomi:  []string{},
		Meanings: []string{"member", "employee", "personnel"},
	},
	{
		Char:     "立",
		Onyomi:   []string{"ritsu", "ryuu"},
		Kunyomi:  []string{"tatsu", "tateru"},
		Meanings: []string{"stand", "stand up"},
	},
	{
		Char:     "開",
		Onyomi:   []string{"kai"},
		Kunyomi:  []string{"hiraku", "aku", "hirakeru"},
		Meanings: []string{"open", "unfold", "unseal"},
	},
	{
		Char:     "手",
		Onyomi:   []string{"shu", "zu"},
		Kunyomi:  []string{"te"},
		Meanings: []string{"hand"},
	},
	{
		Char:     "力",
		Onyomi:   []string{"ryoku", "riki"},
		Kunyomi:  []string{"chikara"},
		Meanings: []string{"power", "strength", "force"},
	},
	{
		Char:     "問",
		Onyomi:   []string{"mon"},
		Kunyomi:  []string{"tou", "toi"},
		Meanings: []string{"question", "ask", "problem"},
	},
	{
		Char:     "代",
		Onyomi:   []string{"dai", "tai"},
		Kunyomi:  []string{"kaeru", "kawaru", "kawari", "yo", "shiro"},
		Meanings: []string{"substitute", "replace", "generation", "age", "fee"},
	},
	{
		Char:     "明",
		Onyomi:   []string{"mei", "myou"},
		Kunyomi:  []string{"akari", "akarui", "akeru", "aku", "akiraka"},
		Meanings: []string{"bright", "light", "clear"},
	},

	// Group 3 (21–30)
	{
		Char:     "動",
		Onyomi:   []string{"dou"},
		Kunyomi:  []string{"ugoku", "ugokasu"},
		Meanings: []string{"move", "motion"},
	},
	{
		Char:     "京",
		Onyomi:   []string{"kyou", "kei"},
		Kunyomi:  []string{"miyako"},
		Meanings: []string{"capital"},
	},
	{
		Char:     "目",
		Onyomi:   []string{"moku", "boku"},
		Kunyomi:  []string{"me"},
		Meanings: []string{"eye"},
	},
	{
		Char:     "通",
		Onyomi:   []string{"tsuu", "tsu"},
		Kunyomi:  []string{"tooru", "toori", "toosu", "kayou"},
		Meanings: []string{"pass through", "traffic", "commute", "avenue"},
	},
	{
		Char:     "言",
		Onyomi:   []string{"gen", "gon"},
		Kunyomi:  []string{"iu"},
		Meanings: []string{"say", "word", "speech"},
	},
	{
		Char:     "理",
		Onyomi:   []string{"ri"},
		Kunyomi:  []string{},
		Meanings: []string{"logic", "reason", "arrangement"},
	},
	{
		Char:     "体",
		Onyomi:   []string{"tai", "tei"},
		Kunyomi:  []string{"karada"},
		Meanings: []string{"body", "form", "object"},
	},
	{
		Char:     "田",
		Onyomi:   []string{"den"},
		Kunyomi:  []string{"ta"},
		Meanings: []string{"rice field", "paddy"},
	},
	{
		Char:     "主",
		Onyomi:   []string{"shu", "su"},
		Kunyomi:  []string{"nushi", "omo"},
		Meanings: []string{"master", "main", "lord", "principal"},
	},
	{
		Char:     "題",
		Onyomi:   []string{"dai"},
		Kunyomi:  []string{},
		Meanings: []string{"topic", "subject", "title", "theme"},
	},

	// Group 4 (31–40)
	{
		Char:     "意",
		Onyomi:   []string{"i"},
		Kunyomi:  []string{},
		Meanings: []string{"idea", "mind", "heart", "thought", "meaning"},
	},
	{
		Char:     "不",
		Onyomi:   []string{"fu", "bu"},
		Kunyomi:  []string{},
		Meanings: []string{"negative", "non-", "bad", "un-"},
	},
	{
		Char:     "作",
		Onyomi:   []string{"saku", "sa"},
		Kunyomi:  []string{"tsukuru"},
		Meanings: []string{"make", "create", "produce", "build"},
	},
	{
		Char:     "用",
		Onyomi:   []string{"you"},
		Kunyomi:  []string{"mochiiru"},
		Meanings: []string{"use", "utilize", "business"},
	},
	{
		Char:     "度",
		Onyomi:   []string{"do", "taku"},
		Kunyomi:  []string{"tabi"},
		Meanings: []string{"degree", "occasion", "time"},
	},
	{
		Char:     "強",
		Onyomi:   []string{"kyou", "gou"},
		Kunyomi:  []string{"tsuyoi", "shiiru"},
		Meanings: []string{"strong", "powerful"},
	},
	{
		Char:     "公",
		Onyomi:   []string{"kou"},
		Kunyomi:  []string{"oyake"},
		Meanings: []string{"public", "official", "formal"},
	},
	{
		Char:     "持",
		Onyomi:   []string{"ji"},
		Kunyomi:  []string{"motsu"},
		Meanings: []string{"hold", "have"},
	},
	{
		Char:     "野",
		Onyomi:   []string{"ya"},
		Kunyomi:  []string{"no"},
		Meanings: []string{"field", "plains"},
	},
	{
		Char:     "以",
		Onyomi:   []string{"i"},
		Kunyomi:  []string{},
		Meanings: []string{"by means of", "compared with", "since"},
	},

	// Group 5 (41–50)
	{
		Char:     "思",
		Onyomi:   []string{"shi"},
		Kunyomi:  []string{"omou"},
		Meanings: []string{"think"},
	},
	{
		Char:     "家",
		Onyomi:   []string{"ka", "ke"},
		Kunyomi:  []string{"ie", "ya"},
		Meanings: []string{"house", "home"},
	},
	{
		Char:     "世",
		Onyomi:   []string{"sei", "se"},
		Kunyomi:  []string{"yo"},
		Meanings: []string{"world", "society", "generation"},
	},
	{
		Char:     "多",
		Onyomi:   []string{"ta"},
		Kunyomi:  []string{"ooi"},
		Meanings: []string{"many", "much"},
	},
	{
		Char:     "正",
		Onyomi:   []string{"sei", "shou"},
		Kunyomi:  []string{"tadashii", "masa"},
		Meanings: []string{"correct", "true", "righteous"},
	},
	{
		Char:     "安",
		Onyomi:   []string{"an"},
		Kunyomi:  []string{"yasui", "yasumaru"},
		Meanings: []string{"cheap", "safe", "peaceful", "relax"},
	},
	{
		Char:     "院",
		Onyomi:   []string{"in"},
		Kunyomi:  []string{},
		Meanings: []string{"institution", "temple", "school", "hospital"},
	},
	{
		Char:     "心",
		Onyomi:   []string{"shin"},
		Kunyomi:  []string{"kokoro"},
		Meanings: []string{"heart", "mind", "spirit"},
	},
	{
		Char:     "界",
		Onyomi:   []string{"kai"},
		Kunyomi:  []string{},
		Meanings: []string{"world", "boundary"},
	},
	{
		Char:     "教",
		Onyomi:   []string{"kyou"},
		Kunyomi:  []string{"oshieru", "osowaru"},
		Meanings: []string{"teach", "instruction", "faith"},
	},

	// Group 6 (51–60)
	{
		Char:     "文",
		Onyomi:   []string{"bun", "mon"},
		Kunyomi:  []string{"fumi"},
		Meanings: []string{"sentence", "literature", "writing"},
	},
	{
		Char:     "元",
		Onyomi:   []string{"gen", "gan"},
		Kunyomi:  []string{"moto"},
		Meanings: []string{"origin", "beginning"},
	},
	{
		Char:     "重",
		Onyomi:   []string{"juu", "chou"},
		Kunyomi:  []string{"omoi", "kasaneru"},
		Meanings: []string{"heavy", "pile", "duplicate"},
	},
	{
		Char:     "近",
		Onyomi:   []string{"kin"},
		Kunyomi:  []string{"chikai"},
		Meanings: []string{"near", "close"},
	},
	{
		Char:     "考",
		Onyomi:   []string{"kou"},
		Kunyomi:  []string{"kangaeru"},
		Meanings: []string{"think", "consider"},
	},
	{
		Char:     "画",
		Onyomi:   []string{"ga", "kaku"},
		Kunyomi:  []string{"egaku", "kakusuru"},
		Meanings: []string{"picture", "drawing", "plan"},
	},
	{
		Char:     "海",
		Onyomi:   []string{"kai"},
		Kunyomi:  []string{"umi"},
		Meanings: []string{"sea", "ocean"},
	},
	{
		Char:     "売",
		Onyomi:   []string{"bai"},
		Kunyomi:  []string{"uru"},
		Meanings: []string{"sell"},
	},
	{
		Char:     "知",
		Onyomi:   []string{"chi"},
		Kunyomi:  []string{"shiru"},
		Meanings: []string{"know", "wisdom"},
	},
	{
		Char:     "道",
		Onyomi:   []string{"dou", "tou"},
		Kunyomi:  []string{"michi"},
		Meanings: []string{"road", "way", "street", "path"},
	},

	// Group 7 (61–70)
	{
		Char:     "集",
		Onyomi:   []string{"shuu"},
		Kunyomi:  []string{"atsumaru", "atsumeru", "tsudou"},
		Meanings: []string{"gather", "collect", "meet"},
	},
	{
		Char:     "別",
		Onyomi:   []string{"betsu"},
		Kunyomi:  []string{"wakareru", "wakeru"},
		Meanings: []string{"separate", "different", "another"},
	},
	{
		Char:     "物",
		Onyomi:   []string{"butsu", "motsu"},
		Kunyomi:  []string{"mono"},
		Meanings: []string{"thing", "object", "matter"},
	},
	{
		Char:     "使",
		Onyomi:   []string{"shi"},
		Kunyomi:  []string{"tsukau"},
		Meanings: []string{"use", "messenger"},
	},
	{
		Char:     "品",
		Onyomi:   []string{"hin"},
		Kunyomi:  []string{"shina"},
		Meanings: []string{"goods", "article", "item"},
	},
	{
		Char:     "計",
		Onyomi:   []string{"kei"},
		Kunyomi:  []string{"hakaru"},
		Meanings: []string{"plan", "measure", "count"},
	},
	{
		Char:     "死",
		Onyomi:   []string{"shi"},
		Kunyomi:  []string{"shinu"},
		Meanings: []string{"death", "die"},
	},
	{
		Char:     "特",
		Onyomi:   []string{"toku"},
		Kunyomi:  []string{},
		Meanings: []string{"special"},
	},
	{
		Char:     "私",
		Onyomi:   []string{"shi"},
		Kunyomi:  []string{"watashi", "watakushi"},
		Meanings: []string{"i", "me", "private"},
	},
	{
		Char:     "始",
		Onyomi:   []string{"shi"},
		Kunyomi:  []string{"hajimaru", "hajimeru"},
		Meanings: []string{"begin", "start"},
	},

	// Group 8 (71–80)
	{
		Char:     "朝",
		Onyomi:   []string{"chou"},
		Kunyomi:  []string{"asa"},
		Meanings: []string{"morning"},
	},
	{
		Char:     "運",
		Onyomi:   []string{"un"},
		Kunyomi:  []string{"hakobu"},
		Meanings: []string{"carry", "transport", "luck"},
	},
	{
		Char:     "終",
		Onyomi:   []string{"shuu"},
		Kunyomi:  []string{"owaru", "oeru"},
		Meanings: []string{"end", "finish"},
	},
	{
		Char:     "台",
		Onyomi:   []string{"dai", "tai"},
		Kunyomi:  []string{"utena"},
		Meanings: []string{"pedestal", "stand", "counter for machines"},
	},
	{
		Char:     "広",
		Onyomi:   []string{"kou"},
		Kunyomi:  []string{"hiroi"},
		Meanings: []string{"wide", "broad", "spacious"},
	},
	{
		Char:     "住",
		Onyomi:   []string{"juu", "chuu"},
		Kunyomi:  []string{"sumu"},
		Meanings: []string{"live", "dwell", "reside"},
	},
	{
		Char:     "無",
		Onyomi:   []string{"mu", "bu"},
		Kunyomi:  []string{"nai"},
		Meanings: []string{"nothing", "without", "non-"},
	},
	{
		Char:     "真",
		Onyomi:   []string{"shin"},
		Kunyomi:  []string{"ma", "makoto"},
		Meanings: []string{"true", "truth", "reality"},
	},
	{
		Char:     "有",
		Onyomi:   []string{"yuu", "u"},
		Kunyomi:  []string{"aru"},
		Meanings: []string{"have", "exist", "possess"},
	},
	{
		Char:     "口",
		Onyomi:   []string{"kou", "ku"},
		Kunyomi:  []string{"kuchi"},
		Meanings: []string{"mouth"},
	},

	// Group 9 (81–90)
	{
		Char:     "少",
		Onyomi:   []string{"shou"},
		Kunyomi:  []string{"sukunai", "sukoshi"},
		Meanings: []string{"few", "little"},
	},
	{
		Char:     "町",
		Onyomi:   []string{"chou"},
		Kunyomi:  []string{"machi"},
		Meanings: []string{"town", "city", "block"},
	},
	{
		Char:     "料",
		Onyomi:   []string{"ryou"},
		Kunyomi:  []string{},
		Meanings: []string{"fee", "materials"},
	},
	{
		Char:     "工",
		Onyomi:   []string{"kou", "ku"},
		Kunyomi:  []string{},
		Meanings: []string{"craft", "construction", "industry"},
	},
	{
		Char:     "建",
		Onyomi:   []string{"ken", "kon"},
		Kunyomi:  []string{"tateru", "tatsu"},
		Meanings: []string{"build", "construct"},
	},
	{
		Char:     "空",
		Onyomi:   []string{"kuu"},
		Kunyomi:  []string{"sora", "aku", "kara", "suku"},
		Meanings: []string{"empty", "sky", "void"},
	},
	{
		Char:     "急",
		Onyomi:   []string{"kyuu"},
		Kunyomi:  []string{"isogu"},
		Meanings: []string{"hurry", "sudden", "urgent"},
	},
	{
		Char:     "止",
		Onyomi:   []string{"shi"},
		Kunyomi:  []string{"tomaru", "tomeru", "todomaru", "todomeru", "yameru", "yamu"},
		Meanings: []string{"stop", "halt"},
	},
	{
		Char:     "送",
		Onyomi:   []string{"sou"},
		Kunyomi:  []string{"okuru"},
		Meanings: []string{"send", "escort"},
	},
	{
		Char:     "切",
		Onyomi:   []string{"setsu", "sai"},
		Kunyomi:  []string{"kiru", "kireru"},
		Meanings: []string{"cut"},
	},

	// Group 10 (91–100)
	{
		Char:     "転",
		Onyomi:   []string{"ten"},
		Kunyomi:  []string{"korogaru", "korobu", "korogasu", "utsuru"},
		Meanings: []string{"turn", "revolve", "tumble"},
	},
	{
		Char:     "研",
		Onyomi:   []string{"ken"},
		Kunyomi:  []string{"togu"},
		Meanings: []string{"polish", "sharpen", "study"},
	},
	{
		Char:     "足",
		Onyomi:   []string{"soku"},
		Kunyomi:  []string{"ashi", "tariru", "taru"},
		Meanings: []string{"foot", "leg", "sufficient"},
	},
	{
		Char:     "究",
		Onyomi:   []string{"kyuu"},
		Kunyomi:  []string{"kiwameru"},
		Meanings: []string{"research", "study"},
	},
	{
		Char:     "楽",
		Onyomi:   []string{"gaku", "raku"},
		Kunyomi:  []string{"tanoshii", "tanoshimu"},
		Meanings: []string{"music", "pleasure", "comfort", "ease"},
	},
	{
		Char:     "起",
		Onyomi:   []string{"ki"},
		Kunyomi:  []string{"okiru", "okosu"},
		Meanings: []string{"wake up", "get up", "rouse"},
	},
	{
		Char:     "着",
		Onyomi:   []string{"chaku", "jaku"},
		Kunyomi:  []string{"kiru", "tsuku", "tsukeru"},
		Meanings: []string{"arrive", "wear", "put on"},
	},
	{
		Char:     "店",
		Onyomi:   []string{"ten"},
		Kunyomi:  []string{"mise"},
		Meanings: []string{"store", "shop"},
	},
	{
		Char:     "病",
		Onyomi:   []string{"byou", "hei"},
		Kunyomi:  []string{"yamu", "yamai"},
		Meanings: []string{"illness", "sick"},
	},
	{
		Char:     "質",
		Onyomi:   []string{"shitsu", "shichi"},
		Kunyomi:  []string{"tachi", "tadasu"},
		Meanings: []string{"quality", "substance", "matter"},
	},

	// Group 11 (101–110)
	{
		Char:     "待",
		Onyomi:   []string{"tai"},
		Kunyomi:  []string{"matsu"},
		Meanings: []string{"wait"},
	},
	{
		Char:     "試",
		Onyomi:   []string{"shi"},
		Kunyomi:  []string{"kokoromiru", "tamesu"},
		Meanings: []string{"test", "try", "attempt"},
	},
	{
		Char:     "族",
		Onyomi:   []string{"zoku"},
		Kunyomi:  []string{},
		Meanings: []string{"tribe", "family"},
	},
	{
		Char:     "銀",
		Onyomi:   []string{"gin"},
		Kunyomi:  []string{"shirogane"},
		Meanings: []string{"silver"},
	},
	{
		Char:     "早",
		Onyomi:   []string{"sou", "satsu"},
		Kunyomi:  []string{"hayai", "hayamaru", "hayameru"},
		Meanings: []string{"early", "fast"},
	},
	{
		Char:     "映",
		Onyomi:   []string{"ei"},
		Kunyomi:  []string{"utsuru", "utsusu", "haeru"},
		Meanings: []string{"reflect", "project", "shine"},
	},
	{
		Char:     "親",
		Onyomi:   []string{"shin"},
		Kunyomi:  []string{"oya", "shitashii"},
		Meanings: []string{"parent", "intimate"},
	},
	{
		Char:     "験",
		Onyomi:   []string{"ken", "gen"},
		Kunyomi:  []string{"akashi", "shirushi", "tamesu"},
		Meanings: []string{"test", "verification"},
	},
	{
		Char:     "英",
		Onyomi:   []string{"ei"},
		Kunyomi:  []string{"hanabusa"},
		Meanings: []string{"england", "english"},
	},
	{
		Char:     "医",
		Onyomi:   []string{"i"},
		Kunyomi:  []string{"iyasu", "isuru", "kusushi"},
		Meanings: []string{"doctor", "medicine"},
	},

	// Group 12 (111–120)
	{
		Char:     "仕",
		Onyomi:   []string{"shi", "ji"},
		Kunyomi:  []string{"tsukaeru"},
		Meanings: []string{"serve", "do", "official"},
	},
	{
		Char:     "去",
		Onyomi:   []string{"kyo", "ko"},
		Kunyomi:  []string{"saru"},
		Meanings: []string{"leave", "go away", "past"},
	},
	{
		Char:     "味",
		Onyomi:   []string{"mi"},
		Kunyomi:  []string{"aji", "ajiwau"},
		Meanings: []string{"taste", "flavor"},
	},
	{
		Char:     "写",
		Onyomi:   []string{"sha", "ja"},
		Kunyomi:  []string{"utsusu", "utsuru"},
		Meanings: []string{"copy", "photograph"},
	},
	{
		Char:     "字",
		Onyomi:   []string{"ji"},
		Kunyomi:  []string{"aza"},
		Meanings: []string{"character", "letter", "word"},
	},
	{
		Char:     "答",
		Onyomi:   []string{"tou"},
		Kunyomi:  []string{"kotaeru"},
		Meanings: []string{"answer", "reply"},
	},
	{
		Char:     "夜",
		Onyomi:   []string{"ya"},
		Kunyomi:  []string{"yo", "yoru"},
		Meanings: []string{"night", "evening"},
	},
	{
		Char:     "音",
		Onyomi:   []string{"on", "in"},
		Kunyomi:  []string{"oto"},
		Meanings: []string{"sound", "noise"},
	},
	{
		Char:     "注",
		Onyomi:   []string{"chuu"},
		Kunyomi:  []string{"sosogu", "sasu", "tsugu"},
		Meanings: []string{"pour", "note", "concentrate"},
	},
	{
		Char:     "帰",
		Onyomi:   []string{"ki"},
		Kunyomi:  []string{"kaeru", "kaesu"},
		Meanings: []string{"return", "go home"},
	},

	// Group 13 (121–130)
	{
		Char:     "古",
		Onyomi:   []string{"ko"},
		Kunyomi:  []string{"furui"},
		Meanings: []string{"old", "ancient"},
	},
	{
		Char:     "歌",
		Onyomi:   []string{"ka"},
		Kunyomi:  []string{"uta", "utau"},
		Meanings: []string{"song", "sing"},
	},
	{
		Char:     "買",
		Onyomi:   []string{"bai"},
		Kunyomi:  []string{"kau"},
		Meanings: []string{"buy"},
	},
	{
		Char:     "悪",
		Onyomi:   []string{"aku", "o"},
		Kunyomi:  []string{"warui", "ashii", "nikui"},
		Meanings: []string{"bad", "evil", "wrong"},
	},
	{
		Char:     "図",
		Onyomi:   []string{"zu", "to"},
		Kunyomi:  []string{"e", "hakaru"},
		Meanings: []string{"map", "drawing", "plan"},
	},
	{
		Char:     "週",
		Onyomi:   []string{"shuu"},
		Kunyomi:  []string{},
		Meanings: []string{"week"},
	},
	{
		Char:     "室",
		Onyomi:   []string{"shitsu"},
		Kunyomi:  []string{"muro"},
		Meanings: []string{"room", "chamber"},
	},
	{
		Char:     "歩",
		Onyomi:   []string{"ho", "bu", "fu"},
		Kunyomi:  []string{"aruku"},
		Meanings: []string{"walk", "step"},
	},
	{
		Char:     "風",
		Onyomi:   []string{"fuu", "fu"},
		Kunyomi:  []string{"kaze"},
		Meanings: []string{"wind", "air", "style"},
	},
	{
		Char:     "紙",
		Onyomi:   []string{"shi"},
		Kunyomi:  []string{"kami"},
		Meanings: []string{"paper"},
	},

	// Group 14 (131–140)
	{
		Char:     "黒",
		Onyomi:   []string{"koku"},
		Kunyomi:  []string{"kuro", "kuroi"},
		Meanings: []string{"black"},
	},
	{
		Char:     "花",
		Onyomi:   []string{"ka", "ke"},
		Kunyomi:  []string{"hana"},
		Meanings: []string{"flower"},
	},
	{
		Char:     "春",
		Onyomi:   []string{"shun", "ha"},
		Kunyomi:  []string{"haru"},
		Meanings: []string{"spring"},
	},
	{
		Char:     "赤",
		Onyomi:   []string{"seki", "shaku"},
		Kunyomi:  []string{"aka", "akai", "akaramu"},
		Meanings: []string{"red"},
	},
	{
		Char:     "青",
		Onyomi:   []string{"sei", "shou"},
		Kunyomi:  []string{"ao"},
		Meanings: []string{"blue", "green"},
	},
	{
		Char:     "館",
		Onyomi:   []string{"kan"},
		Kunyomi:  []string{"yakata"},
		Meanings: []string{"building", "mansion", "hall"},
	},
	{
		Char:     "屋",
		Onyomi:   []string{"oku"},
		Kunyomi:  []string{"yane"},
		Meanings: []string{"roof", "house", "shop"},
	},
	{
		Char:     "色",
		Onyomi:   []string{"shoku", "shiki"},
		Kunyomi:  []string{"iro"},
		Meanings: []string{"color"},
	},
	{
		Char:     "走",
		Onyomi:   []string{"sou"},
		Kunyomi:  []string{"hashiru"},
		Meanings: []string{"run"},
	},
	{
		Char:     "秋",
		Onyomi:   []string{"shuu"},
		Kunyomi:  []string{"aki"},
		Meanings: []string{"autumn", "fall"},
	},

	// Group 15 (141–150)
	{
		Char:     "夏",
		Onyomi:   []string{"ka", "ga"},
		Kunyomi:  []string{"natsu"},
		Meanings: []string{"summer"},
	},
	{
		Char:     "習",
		Onyomi:   []string{"shuu", "ju"},
		Kunyomi:  []string{"narau"},
		Meanings: []string{"learn", "practice"},
	},
	{
		Char:     "駅",
		Onyomi:   []string{"eki"},
		Kunyomi:  []string{},
		Meanings: []string{"station"},
	},
	{
		Char:     "洋",
		Onyomi:   []string{"you"},
		Kunyomi:  []string{},
		Meanings: []string{"ocean", "western style"},
	},
	{
		Char:     "旅",
		Onyomi:   []string{"ryo"},
		Kunyomi:  []string{"tabi"},
		Meanings: []string{"trip", "travel", "journey"},
	},
	{
		Char:     "服",
		Onyomi:   []string{"fuku"},
		Kunyomi:  []string{},
		Meanings: []string{"clothes", "clothing", "obey"},
	},
	{
		Char:     "夕",
		Onyomi:   []string{"seki", "yuu"},
		Kunyomi:  []string{"yuu", "yube"},
		Meanings: []string{"evening"},
	},
	{
		Char:     "借",
		Onyomi:   []string{"shaku"},
		Kunyomi:  []string{"kariru"},
		Meanings: []string{"borrow", "rent"},
	},
	{
		Char:     "曜",
		Onyomi:   []string{"you"},
		Kunyomi:  []string{},
		Meanings: []string{"weekday", "day of week"},
	},
	{
		Char:     "飲",
		Onyomi:   []string{"in", "on"},
		Kunyomi:  []string{"nomu"},
		Meanings: []string{"drink"},
	},

	// Group 16 (151–160)
	{
		Char:     "肉",
		Onyomi:   []string{"niku"},
		Kunyomi:  []string{},
		Meanings: []string{"meat"},
	},
	{
		Char:     "貸",
		Onyomi:   []string{"tai"},
		Kunyomi:  []string{"kasu"},
		Meanings: []string{"lend", "loan"},
	},
	{
		Char:     "堂",
		Onyomi:   []string{"dou"},
		Kunyomi:  []string{},
		Meanings: []string{"hall", "public chamber"},
	},
	{
		Char:     "鳥",
		Onyomi:   []string{"chou", "to"},
		Kunyomi:  []string{"tori"},
		Meanings: []string{"bird", "chicken"},
	},
	{
		Char:     "飯",
		Onyomi:   []string{"han"},
		Kunyomi:  []string{"meshi"},
		Meanings: []string{"meal", "rice"},
	},
	{
		Char:     "勉",
		Onyomi:   []string{"ben"},
		Kunyomi:  []string{"tsutomeru"},
		Meanings: []string{"exertion", "effort"},
	},
	{
		Char:     "冬",
		Onyomi:   []string{"tou"},
		Kunyomi:  []string{"fuyu"},
		Meanings: []string{"winter"},
	},
	{
		Char:     "昼",
		Onyomi:   []string{"chuu"},
		Kunyomi:  []string{"hiru"},
		Meanings: []string{"daytime", "noon"},
	},
	{
		Char:     "茶",
		Onyomi:   []string{"cha"},
		Kunyomi:  []string{},
		Meanings: []string{"tea"},
	},
	{
		Char:     "弟",
		Onyomi:   []string{"tei", "dai"},
		Kunyomi:  []string{"otouto"},
		Meanings: []string{"younger brother"},
	},

	// Group 17 (161–167)
	{
		Char:     "牛",
		Onyomi:   []string{"gyuu", "u"},
		Kunyomi:  []string{"ushi"},
		Meanings: []string{"cow", "cattle", "beef"},
	},
	{
		Char:     "魚",
		Onyomi:   []string{"gyo"},
		Kunyomi:  []string{"uo", "sakana"},
		Meanings: []string{"fish"},
	},
	{
		Char:     "兄",
		Onyomi:   []string{"kei", "kyou"},
		Kunyomi:  []string{"ani"},
		Meanings: []string{"elder brother"},
	},
	{
		Char:     "犬",
		Onyomi:   []string{"ken"},
		Kunyomi:  []string{"inu"},
		Meanings: []string{"dog"},
	},
	{
		Char:     "妹",
		Onyomi:   []string{"mai"},
		Kunyomi:  []string{"imouto"},
		Meanings: []string{"younger sister"},
	},
	{
		Char:     "姉",
		Onyomi:   []string{"shi"},
		Kunyomi:  []string{"ane", "haha"},
		Meanings: []string{"elder sister"},
	},
	{
		Char:     "漢",
		Onyomi:   []string{"kan"},
		Kunyomi:  []string{},
		Meanings: []string{"china", "sino-", "chinese"},
	},
}

var N4Groups = [][]Kanji{
	N4[0:10],
	N4[10:20],
	N4[20:30],
	N4[30:40],
	N4[40:50],
	N4[50:60],
	N4[60:70],
	N4[70:80],
	N4[80:90],
	N4[90:100],
	N4[100:110],
	N4[110:120],
	N4[120:130],
	N4[130:140],
	N4[140:150],
	N4[150:160],
	N4[160:167],
}
