version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/kanarenshu
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: git
  abbrev: 7
  groups:
    - title: "✨ Features"
      regexp: '^feat(\(.+\))?:'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^fix(\(.+\))?:'
      order: 1
    - title: "🧹 Chores & Refactors"
      regexp: '^(chore|refactor|perf)(\(.+\))?:'
      order: 2
    - title: "Other"
      regexp: ".*"
      order: 999
  format: "* {{ .Message }}"
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^Merge pull request"
      - "^Merge branch"

aurs:
  - name: kanarenshu-bin
    homepage: "https://github.com/nuixyz/kanarenshu"
    description: "A minimal TUI application to practise Japanese from the terminal."
    maintainers:
      - "nuixyz"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/kanarenshu-bin.git"
    provides:
      - kanarenshu
    conflicts:
      - kanarenshu
    package: |-
      install -Dm755 "./kanarenshu" "${pkgdir}/usr/bin/kanarenshu"
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/kanarenshu/README.md"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/kanarenshu/LICENSE"
    commit_author:
      name: nuixyz
      email: contactme@nuixyz.dev
    commit_msg_template: "kananrenshu-bin: updated to {{ .Tag }}"
    goamd64: v1
